version: '3'

services:
  caster_service:
    image: ubuntu:24.04 # 使用空的容器镜像
    container_name: caster_container
    ports:
      - "4202:4202" # 你可以将这个端口号替换为你想要的外部端口号
    volumes:
      - ./app:/app  # 将当前目录下的 app 子目录挂载到容器的 /app      
    depends_on:
      - redis
    command: ["/app/Caster_Service"]  # 这里替换为你的可执行程序名称
    restart: always
    privileged: true  # 添加特权模式
    networks:
      - caster_network

  redis:
    image: redis:7.4.0 # 使用空的容器镜像
    container_name: redis_container
    ports:
      - "16379:6379"
    privileged: true  
    volumes:
      - ./app/env:/app/env  # 将你的自定义配置文件挂载到容器中
    command: ["redis-server"] #, "/app/env/redis/redis.config"]  # 使用自定义配置文件启动Redis
    restart: always
    sysctls:
      - net.core.somaxconn=1024
   #   - vm.overcommit_memory=1  # 启用内存过度分配
    cap_add:
      - SYS_PTRACE
      - SYS_RESOURCE  # 允许增加系统资源的使用
    networks:
      - caster_network

networks:
  caster_network:
    driver: bridge