name: Build aarch64 executable

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: aarch64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build executable for aarch64
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 -t my-aarch64-app .

    - name: Run build commands
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace my-aarch64-app /bin/bash -c "
          apt-get update &&
          apt-get install -y build-essential cmake &&
          mkdir -p build &&
          cd build &&
          cmake .. &&
          make"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/
