# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4.1.4
      with:
        fetch-depth: 0
        fetch-tags: true  # 获取所有的 Git 标签
        submodules: true  # 拉取子模块
        

    - name: Build APP
      run: |
        chmod +x ci/build.sh
        ci/build.sh

    - name: Build Env
      # Build your program with the given configuration
      run: cd ${{github.workspace}}/env/redis-7.2.1 && make MALLOC=libc

    - name: Pack Env
      run: |
       cp ${{github.workspace}}/env/redis-7.2.1/src/redis-server ${{github.workspace}}/bin/env
       cp ${{github.workspace}}/env/start-redis.sh ${{github.workspace}}/bin/env
       cp ${{github.workspace}}/env/stop-redis.sh ${{github.workspace}}/bin/env
       
    - name: Get Tag Version
      id: tag_version
      run: echo "::set-output name=tag_version::$(git describe --tags --dirty=-dev)"

    - name: Upload Release
      uses: actions/upload-artifact@v4.3.3
      with:
        # 上传后文件的名称
        name: Caster_Service-${{ steps.tag_version.outputs.tag_version }}-ububtu-gcc
        # 上传文件的路径
        path: ${{github.workspace}}/bin/
